<wsdl:definitions
     name="QueryCreditStatus"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Labs12cApp/L01-DBAdapter/QueryCreditStatus"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Labs12cApp/L01-DBAdapter/QueryCreditStatus"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryCreditStatus"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="QueryCreditStatus_plt" >
    <plt:role name="QueryCreditStatus_role" >
      <plt:portType name="tns:QueryCreditStatus_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/QueryCreditStatus" schemaLocation="../Schemas/QueryCreditStatus_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="QueryCreditStatusSelect_inputParameters">
        <wsdl:part name="QueryCreditStatusSelect_inputParameters" element="top:QueryCreditStatusSelect_ccnrInputParameters"/>
    </wsdl:message>
    <wsdl:message name="CreditcardinfoCollection_msg">
        <wsdl:part name="CreditcardinfoCollection" element="top:CreditcardinfoCollection"/>
    </wsdl:message>
    <wsdl:portType name="QueryCreditStatus_ptt">
        <wsdl:operation name="QueryCreditStatusSelect">
            <wsdl:input message="tns:QueryCreditStatusSelect_inputParameters"/>
            <wsdl:output message="tns:CreditcardinfoCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
